# Runtime paramters
run:
  # Number of runs
  runs: 2000
  # Num of steps each run
  steps: 1000

# Parameters for the k-armed bandit
bandit:
  # Number of arms
  n_arms: 10

# Parameters each arm of the bandit
arm:
  # Mean of the distribution for action values of an arm
  mean: 0
  # Variance of the distribution for action values of an arm
  var: 1
  # Non-stationary mean. The action values change by the every step
  ns_mean: 0
  # Non-stationary variance
  ns_var: 0.01
